
version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
    image: cirepo/jenkins:2.124-alpine
    restart: always
    container_name: ${JENKINS_DOMAIN:-jenkins}.${INFRASTRUCTURE:-local}
    hostname: ${JENKINS_DOMAIN:-jenkins}.${INFRASTRUCTURE:-local}
    ports:
    - "${JENKINS_EXTERNAL_PORT:-18083}:${JENKINS_PORT:-8080}"
    - "50000:50000/tcp"
    volumes:
    - volume-jenkins-master:/var/jenkins_home
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000

volumes:
  volume-jenkins-master: {}

networks:
  default:
    external: true
    name: oss-network
